import streamlit as st
import dns.resolver
import requests
import ssl
import socket
import datetime
import io
import re
import pandas as pd
import whois  # New Library
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from urllib.parse import urlparse, quote

# --- CONFIGURATION ---
st.set_page_config(page_title="V-GUARD | OSINT Audit", page_icon="🛡️", layout="wide")
MY_WHATSAPP = "201102353779"
MY_EMAIL = "amarhossam0000@gmail.com"

# --- PDF GENERATION FUNCTION ---
def create_pdf(domain, results, server_info, whois_info, score):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "V-GUARD INTELLIGENCE")
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 75, f"Security Score: {score}/100")
    
    if score < 50: grade = "CRITICAL RISK"
    elif score < 80: grade = "NEEDS ATTENTION"
    else: grade = "SECURE"
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 95, f"Grade: {grade}")
    c.line(50, height - 105, 550, height - 105)

    # General Info
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 130, f"Target: {domain}")
    c.drawString(50, height - 145, f"IP: {server_info.get('ip', 'N/A')}")
    c.drawString(50, height - 160, f"Loc: {server_info.get('city', 'N/A')}, {server_info.get('country', 'N/A')}")
    
    # New Section: Domain Intel
    y = height - 200
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "1. Domain Intelligence (WHOIS)")
    c.setFont("Helvetica", 12)
    y -= 25
    c.drawString(70, y, f"Registered On: {whois_info.get('creation_date', 'Hidden')}")
    y -= 20
    c.drawString(70, y, f"Expires On: {whois_info.get('expiration_date', 'Hidden')}")
    y -= 20
    c.drawString(70, y, f"Registrar: {whois_info.get('registrar', 'Unknown')}")

    # Section 2: DNS
    y -= 50
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "2. DNS Security")
    c.setFont("Helvetica", 12)
    y -= 25
    c.drawString(70, y, f"SPF: {results['spf']}")
    y -= 20
    c.drawString(70, y, f"DMARC: {results['dmarc']}")

    # Section 3: SSL
    y -= 50
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "3. SSL Encryption")
    c.setFont("Helvetica", 12)
    y -= 25
    c.drawString(70, y, f"Status: {results['ssl_status']}")
    
    # Footer
    c.line(50, 100, 550, 100)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 80, "Generated by V-Guard System | Contact: +201102353779")

    c.save()
    buffer.seek(0)
    return buffer

# --- SIDEBAR ---
with st.sidebar:
    st.title("V-GUARD 🛡️")
    st.metric("Version", "7.0 (OSINT)")
    st.markdown(f"[Chat on WhatsApp](https://wa.me/{MY_WHATSAPP})")

# --- MAIN APP ---
st.title("🛡️ V-GUARD INTELLIGENCE SYSTEM")
st.markdown("#### Advanced Cyber Reconnaissance & Audit Tool")

tab1, tab2, tab3 = st.tabs(["🌐 Full Site Audit", "🔑 Password Lab", "📞 Client Support"])

# =========================================
# TAB 1: AUDIT + WHOIS + SCORE
# =========================================
with tab1:
    target_input = st.text_input("Enter Target URL/Email", placeholder="company.com")
    
    if st.button("INITIATE FULL SCAN 🚀", type="primary"):
        if not target_input:
            st.warning("⚠️ Please enter a target.")
        else:
            domain = None
            if "@" in target_input and not target_input.startswith("http"):
                domain = target_input.split("@")[1]
            else:
                if not target_input.startswith(("http", "www")): target_input = "https://" + target_input
                try: domain = urlparse(target_input).netloc
                except: domain = None
            
            if domain:
                st.success(f"🎯 Target Locked: {domain}")
                
                # Data Containers
                security_score = 0
                scan_data = {"spf": "Missing ❌", "dmarc": "Missing ❌", "ssl_status": "Not Secure ❌"}
                server_data = {"ip": "N/A", "city": "N/A", "country": "N/A"}
                whois_data = {"creation_date": "N/A", "expiration_date": "N/A", "registrar": "N/A"}

                # --- 1. DOMAIN INTELLIGENCE (WHOIS) ---
                try:
                    w = whois.whois(domain)
                    # Handle lists (some domains return lists of dates)
                    c_date = w.creation_date
                    if isinstance(c_date, list): c_date = c_date[0]
                    
                    e_date = w.expiration_date
                    if isinstance(e_date, list): e_date = e_date[0]

                    whois_data['creation_date'] = str(c_date)
                    whois_data['expiration_date'] = str(e_date)
                    whois_data['registrar'] = w.registrar
                    
                    # Score Logic: Old domains (>1 year) are safer
                    if c_date:
                        age_days = (datetime.datetime.now() - c_date).days
                        if age_days > 365: security_score += 10
                except:
                    pass # Whois privacy enabled

                # --- 2. SERVER TRACKER ---
                try:
                    ip = socket.gethostbyname(domain)
                    server_data['ip'] = ip
                    geo = requests.get(f"http://ip-api.com/json/{ip}").json()
                    if geo['status'] == 'success':
                        server_data['city'] = geo['city']
                        server_data['country'] = geo['country']
                except: pass

                # --- 3. SECURITY SCANS ---
                # DNS
                try:
                    ans = dns.resolver.resolve(domain, 'TXT')
                    for r in ans:
                        if "v=spf1" in r.to_text():
                            scan_data['spf'] = "Active ✅"
                            security_score += 30
                except: pass

                try:
                    dns.resolver.resolve(f"_dmarc.{domain}", 'TXT')
                    scan_data['dmarc'] = "Active ✅"
                    security_score += 30
                except: pass

                # SSL
                try:
                    ctx = ssl.create_default_context()
                    with ctx.wrap_socket(socket.socket(), server_hostname=domain) as s:
                        s.settimeout(3.0)
                        s.connect((domain, 443))
                        security_score += 30
                        scan_data['ssl_status'] = "Valid ✅"
                except: pass

                # --- DISPLAY RESULTS ---
                c1, c2 = st.columns([1, 2])
                with c1:
                    st.metric("🛡️ SECURITY SCORE", f"{security_score}/100")
                    if security_score < 50: st.error("CRITICAL RISK")
                    else: st.success("SECURE")
                
                with c2:
                    st.write("### 🕵️‍♂️ Domain Intelligence")
                    st.info(f"**Registrar:** {whois_data['registrar']}")
                    st.info(f"**Created:** {whois_data['creation_date']}")
                    st.info(f"**Server Loc:** {server_data['city']}, {server_data['country']}")

                st.markdown("---")
                
                # --- PDF REPORT ---
                pdf_bytes = create_pdf(domain, scan_data, server_data, whois_data, security_score)
                st.download_button("📄 DOWNLOAD OFFICIAL REPORT", pdf_bytes, f"VGuard_{domain}.pdf", "application/pdf")

# =========================================
# TAB 2 & 3 (Standard)
# =========================================
with tab2:
    st.header("Password Strength Analysis")
    password = st.text_input("Enter Password", type="password")
    if st.button("ANALYZE"):
        # Simple Logic for brevity
        if len(password) > 8: st.success("Strong Password")
        else: st.error("Weak Password")

with tab3:
    st.header("Contact Us")
    st.link_button("WhatsApp Support 💬", f"https://wa.me/{MY_WHATSAPP}")
