import streamlit as st
import dns.resolver
import requests
import ssl
import socket
import datetime
import io
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from urllib.parse import urlparse

# --- CONFIGURATION ---
st.set_page_config(page_title="V-GUARD | Global Intel", page_icon="🛡️", layout="wide")
MY_WHATSAPP = "201102353779"

# --- HELPER FUNCTIONS ---
def get_geolocation(domain):
    try:
        ip = socket.gethostbyname(domain)
        response = requests.get(f"http://ip-api.com/json/{ip}")
        data = response.json()
        return data['lat'], data['lon'], data['city'], data['country'], data['isp']
    except:
        return None, None, "Unknown", "Unknown", "Hidden"

def create_pdf(domain, results):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "V-GUARD INTELLIGENCE")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 70, "Professional Cyber Security Audit Report")
    c.line(50, height - 80, 550, height - 80)
    c.drawString(50, height - 110, f"Target: {domain}")
    c.drawString(50, height - 130, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d')}")
    
    y = height - 170
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "EXECUTIVE SUMMARY:")
    y -= 30
    c.setFont("Helvetica", 12)
    c.drawString(60, y, f"• Security Score: {results['score']}/100")
    c.drawString(60, y-20, f"• SPF Status: {results['spf']}")
    c.drawString(60, y-40, f"• DMARC Status: {results['dmarc']}")
    c.drawString(60, y-60, f"• SSL/TLS: {results['ssl_status']}")
    c.drawString(60, y-80, f"• Server Location: {results['location']}")
    
    c.line(50, 100, 550, 100)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 80, "Report generated by V-Guard System.")
    c.save()
    buffer.seek(0)
    return buffer

# --- MAIN APP ---
st.title("🛡️ V-GUARD INTELLIGENCE SYSTEM")
st.markdown("#### Advanced Cyber Reconnaissance & Audit Tool")

tab1, tab2, tab3 = st.tabs(["🌍 Full Site Audit", "🔑 Password Lab", "📞 Client Support"])

# ================= TAB 1: FULL AUDIT =================
with tab1:
    target_input = st.text_input("Enter Target URL/Email", placeholder="https://company.com")
    
    if st.button("INITIATE FULL SCAN 🚀", type="primary"):
        if not target_input:
            st.warning("Please enter a target.")
        else:
            # 1. Domain Extraction
            domain = None
            if "@" in target_input and not target_input.startswith("http"):
                domain = target_input.split("@")[1]
            else:
                if not target_input.startswith(("http", "www")): target_input = "https://" + target_input
                try: domain = urlparse(target_input).netloc
                except: domain = None
            
            if domain:
                st.success(f"Target Locked: {domain}")
                
                # 2. DATA COLLECTION
                score = 0
                scan_data = {"location": "Unknown"}
                
                # --- DNS & SCORE CALCULATION ---
                spf_status = "Missing ❌"
                try:
                    ans = dns.resolver.resolve(domain, 'TXT')
                    for r in ans:
                        if "v=spf1" in r.to_text():
                            spf_status = "Active ✅"
                            score += 25
                except: pass
                
                dmarc_status = "Missing ❌"
                try:
                    dns.resolver.resolve(f"_dmarc.{domain}", 'TXT')
                    dmarc_status = "Active ✅"
                    score += 25
                except: pass
                
                # --- SSL CHECK ---
                ssl_status = "Not Secure ❌"
                days_left = 0
                try:
                    ctx = ssl.create_default_context()
                    with ctx.wrap_socket(socket.socket(), server_hostname=domain) as s:
                        s.settimeout(3.0)
                        s.connect((domain, 443))
                        cert = s.getpeercert()
                        edate = datetime.datetime.strptime(cert['notAfter'], '%b %d %H:%M:%S %Y %Z')
                        days_left = (edate - datetime.datetime.now()).days
                        ssl_status = "Valid ✅"
                        score += 25
                except: pass

                # --- HEADERS ---
                headers_status = "Weak ⚠️"
                try:
                    r = requests.get(f"https://{domain}", timeout=5)
                    if 'X-Frame-Options' in r.headers:
                        score += 25
                        headers_status = "Strong ✅"
                except: pass

                # --- GEOLOCATION (THE MAP!) ---
                lat, lon, city, country, isp = get_geolocation(domain)
                scan_data['location'] = f"{city}, {country}"

                # 3. VISUALIZATION
                
                # SECTION A: SCORE & MAP
                c1, c2 = st.columns([1, 2])
                with c1:
                    st.metric("SECURITY SCORE", f"{score}/100", delta="Critical" if score < 50 else "Good")
                    if score < 50:
                        st.error("CRITICAL RISK DETECTED")
                    else:
                        st.success("SYSTEM SECURE")
                    
                    st.write("---")
                    st.caption("SERVER INTELLIGENCE")
                    st.write(f"**ISP:** {isp}")
                    st.write(f"**Location:** {city}, {country}")

                with c2:
                    st.subheader("📍 Server Geolocation")
                    if lat and lon:
                        map_data = pd.DataFrame({'lat': [lat], 'lon': [lon]})
                        st.map(map_data, zoom=4)
                    else:
                        st.warning("Could not trace server location.")

                st.markdown("---")

                # SECTION B: DETAILED TECHNICAL DATA (The Old Stuff)
                st.subheader("🔍 Technical Vulnerability Report")
                
                col_dns, col_ssl, col_head = st.columns(3)
                
                with col_dns:
                    st.info("📡 DNS Security")
                    st.write(f"**SPF Record:** {spf_status}")
                    st.write(f"**DMARC Policy:** {dmarc_status}")
                    if spf_status == "Missing ❌": st.caption("Risk: Email Spoofing")
                
                with col_ssl:
                    st.info("🔒 SSL Encryption")
                    st.write(f"**Status:** {ssl_status}")
                    if ssl_status == "Valid ✅":
                        st.write(f"**Expires In:** {days_left} days")
                
                with col_head:
                    st.info("🛡️ HTTP Headers")
                    st.write(f"**Protection Level:** {headers_status}")
                    st.caption("Checked: Anti-Clickjacking")

                st.markdown("---")
                
                # SECTION C: REPORT
                report_data = {
                    "score": score, "spf": spf_status, "dmarc": dmarc_status,
                    "ssl_status": ssl_status, "location": scan_data['location']
                }
                pdf = create_pdf(domain, report_data)
                st.download_button("📄 DOWNLOAD OFFICIAL REPORT (PDF)", pdf, file_name="VGuard_Report.pdf")

# ================= TAB 2 & 3 (Standard) =================
with tab2:
    st.header("Password Lab")
    st.text_input("Test Password", type="password")
    st.info("Enter password to analyze entropy.")

with tab3:
    st.header("Contact Us")
    st.markdown(f"[Chat on WhatsApp](https://wa.me/{MY_WHATSAPP})")
